services:
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-rocktseat-ama-go-react:/var/lib/postgresql/data

volumes:
  postgres-rocktseat-ama-go-react:
    driver: local
